# Generated by Django 4.0.4 on 2022-10-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('science', 'Science'), ('politics', 'Politics'), ('religion', 'Religion'), ('technology', 'Technology'), ('music', 'Music')], default='', max_length=255)),
                ('keywords', models.CharField(default='', max_length=255)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('thumbnail_image', models.FileField(default='', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
