# Generated by Django 4.0.4 on 2022-10-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='test',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
