# Generated by Django 4.0.4 on 2022-10-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='test',
        ),
    ]
